apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
    namespace: monitoring
  creationTimestamp: null
  labels:
    io.kompose.service: tempo
  name: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tempo
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
        namespace: monitoring
      creationTimestamp: null
      labels:
        io.kompose.service: tempo
    spec:
      containers:
        - args:
            - --target=all
            - --storage.trace.backend=local
            - --storage.trace.local.path=/var/tempo
            - --auth.enabled=false
            - --compactor.compaction.block-retention=24h
          image: grafana/tempo:1.1.0
          name: tempo
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
