apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payment-service
  name: payment-service
  namespace: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - image: yohaim1511/payment-service:0.1
        name: payment-service
        ports:
        - containerPort: 5000
        resources: # Verify the amount of requests
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: OTLP
          value: "otel-collector.otel-collector.svc.cluster.local"
        - name: DATABASE
          value: "database-service.database-service.svc.cluster.local"
        - name: LOGS
          value: "analytics-service.analytics-service.svc.cluster.local" # Analytics Service
        - name: INVENTORY
          value: "inventory-service.inventory-service.svc.cluster.local"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: payment-service
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: payment-service
