apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: db
  template:
    metadata:
      labels:
        name: db
    spec:
      containers:
      - name: db
        image: grafana/tns-db:latest
        imagePullPolicy: IfNotPresent
        args:
        - -log.level=debug
        ports:
        - name: http-metrics
          containerPort: 80
        env:
        - name: JAEGER_AGENT_HOST
          value: tempo.default.svc.cluster.local
        - name: JAEGER_TAGS
          value: cluster=docker,namespace=default
        - name: JAEGER_SAMPLER_TYPE
          value: const
        - name: JAEGER_SAMPLER_PARAM
          value: "1"
